### ISSUE TITLE
Run out-of-memory

### ISSUE THREAD

**Issue by lf-openthos** [JustinhoCHN/SRGAN_Wasserstein#15]
I'm using a computer with 16GB RAM and GTX1070 with 8GB VRAM, some related LOG is here:

> 2019-04-25 18:55:03.366302: I tensorflow/core/common_runtime/bfc_allocator.cc:683] Sum Total of in-use chunks: 2.64GiB
2019-04-25 18:55:03.366314: I tensorflow/core/common_runtime/bfc_allocator.cc:685] Stats: 
Limit:                  2834107269
InUse:                  2831626496
MaxInUse:               2831626496
NumAllocs:                    1737
MaxAllocSize:            426749696

> 2019-04-25 18:55:03.366400: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ****************************************************************************************************
2019-04-25 18:55:03.366421: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[16,64,96,96]
Traceback (most recent call last):
  File "/home/lf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/lf/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/lf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16,64,96,96]
         [[Node: SRGAN_g/n64s1/c1/3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](SRGAN_g/b_residual_add/2, SRGAN_g/n64s1/c1/3/W_conv2d/read)]]
         [[Node: mean_squared_error_loss/Mean_1/_83 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_8324_mean_squared_error_loss/Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by lf-openthos** [comment]
It's my fault, after unset the wrong GPU option and reduce batch_size to 4, everything goes.
