### ISSUE TITLE
line 53/35 mod doesn't work

### ISSUE THREAD

**Issue by ManoaNosea** [JustinhoCHN/SRGAN_Wasserstein#7]
```
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 9 and 3. Shapes are [9,9,3,64] and [3,3,3,64]. for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [3,3,3,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 353, in <module>
    train()
  File "main.py", line 322, in evaluate
    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=False))
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\wasserstein-1\tensorlayer\files.py", line 723, in load_and_assign_npz
    assign_params(sess, params, network)
  File "Y:\theshitt-backup\Projects\AINeuralNetSuperRes\wasserstein-1\tensorlayer\files.py", line 692, in assign_params
    ops.append(network.all_params[idx].assign(param))
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\variables.py", line 615, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\state_ops.py", line 283, in assign
    validate_shape=validate_shape)
  File "C:\Python35\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 63, in assign
    use_locking=use_locking, name=name)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1734, in __init__
    control_input_ops)
  File "C:\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 9 and 3. Shapes are [9,9,3,64] and [3,3,3,64]. for 'Assign' (op: 'Assign') with input shapes: [9,9,3,64], [3,3,3,64].
```

**Comment by JustinhoCHN** [comment]
Have you write any custom code? If you follow the procedure from readme, won't raise the error like that. I recommend you to run my main.py first, without any modification. Once you success, you can try the different dataset.

**Comment by TrojanXu** [comment]
should be line 53/24
